# NOTE: arm images haven't been tested
services:
  faster-whisper-server-cuda:
    image: fedirz/faster-whisper-server:cuda-0.1
    build:
      dockerfile: Dockerfile.cuda
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
  faster-whisper-server-cpu:
    image: fedirz/faster-whisper-server:cpu-0.1
    build:
      dockerfile: Dockerfile.cpu
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    ports:
      - 8000:8000
